/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.Cleint;
import models.Hiber;
import models.Reeltor;
import models.User;

/**
 *
 * @author WSR
 */
public class ClientRegDialog extends javax.swing.JDialog {

    private Integer phon = 0;
    private boolean flag = true;
    
    /**
     * Creates new form ClientRegDialog
     */
    public ClientRegDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        FirstField1 = new javax.swing.JTextField();
        LastField2 = new javax.swing.JTextField();
        MiddleField3 = new javax.swing.JTextField();
        PhoneField4 = new javax.swing.JTextField();
        MailField5 = new javax.swing.JTextField();
        LogField6 = new javax.swing.JTextField();
        PasRepField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PasField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton3.setText("Выход");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        LastField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastField2ActionPerformed(evt);
            }
        });

        MailField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailField5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Имя:");

        jLabel2.setText("Фамилия");

        jLabel3.setText("Отчество");

        jLabel4.setText("Телефон");

        jLabel5.setText("email");

        jLabel6.setText("логин");

        jLabel7.setText("пароль");

        jLabel8.setText("Повторите пароль");

        jButton1.setText("Отмена");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Я риэлтор");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Зарегистрироваться");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FirstField1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(MiddleField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MailField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastField2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PasRepField7, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(LogField6)
                            .addComponent(PasField8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(170, 170, 170)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MiddleField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MailField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LogField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasRepField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Hiber.ShutDown();
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LastField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MailField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        flag = !flag; 
        if (flag){
            jButton2.setText("Я риэлтор");
            jLabel4.setText("Телефон");
            jLabel5.setVisible(true);
            MailField5.setVisible(true);
        } else {           
            jButton2.setText("Я клиент");
            jLabel5.setVisible(false);
            MailField5.setVisible(false);
            jLabel4.setText("Комиссия");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Регистрация и проверка условий клиента и риэлтора 
        System.out.println(flag);
        if (!flag){        //Риэлтор               
            String fname = FirstField1.getText();
            String mname = MiddleField3.getText();
            String lname = LastField2.getText();
            //Проверка на заполненность ФИО
            if (fname.equals("")||mname.equals("")||lname.equals("")){
                JOptionPane.showMessageDialog(this, "Поля "
                        + "\"Имя\", \"Фамилия\" и \"Отчество\" "
                        + "не должны быть пустыми!");
                return;
            }
            //Проверка поля Комиссия
            try {
                phon = Integer.parseInt(PhoneField4.getText());
                if ((phon > 100) || (PhoneField4.getText().equals("")) ||
                        (phon < 0)){
                    JOptionPane.showMessageDialog(this, "Комиссия должна "
                        + "быть от 0 до 100");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "В поле \"Комиссия\""
                        + " должно быть число");
                return;
            }
            String log = LogField6.getText();
            String pas = PasField8.getText();
            String repPas = PasRepField7.getText();
            //Проверка на заполненность в полях логин, пароль и повтор пароля
            if (log.equals("")||pas.equals("")||repPas.equals("")){
                JOptionPane.showMessageDialog(this, "Поля "
                        + "\"Логин\", \"Пароль\" и \"Повторите пароль\" "
                        + "не должны быть пустыми!");
                return;
            }
            //Проверка на совпадение паролей
            if (!pas.equals(repPas)){
                JOptionPane.showMessageDialog(this, "Пароли не совпадают");
                return;
            }
            List<User> listUser = Hiber.session.createQuery("from User "
                + "where login like '"+log+"'").list();
            if (listUser.isEmpty()){
            Reeltor reelt = new Reeltor(log,pas,fname,mname,lname,phon);        
            Hiber.Save(reelt);
            } else {
                JOptionPane.showMessageDialog(this, "Такой логин уже занят!");
                return;
            }
        } else { //Клиент
            String fname = FirstField1.getText();
            String mname = MiddleField3.getText();
            String lname = LastField2.getText();
            String mail = MailField5.getText();
            System.out.println("phon "+PhoneField4.getText() + "; email "+mail);
            if (PhoneField4.getText().equals("")&&mail.equals("")){
                JOptionPane.showMessageDialog(this, "Заполните "
                        + "\"Номер телефона\"  или \"email\"");
                return;
            }
            if (!PhoneField4.getText().equals(""))
                try {
                    Integer phon = Integer.parseInt(PhoneField4.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Телефон должен состоять "
                            + "из цифр");
                    return;
                }            
            
            if (!checkMail(mail)&&!mail.equals("")){
                JOptionPane.showMessageDialog(this, "Неправильно введён email."
                        + "Пример написания: example@examp.ex");
                return;
            }                        
            String log = LogField6.getText();
            String pas = PasField8.getText();
            String repPas = PasRepField7.getText();
            if (log.equals("")||pas.equals("")||repPas.equals("")){
                JOptionPane.showMessageDialog(this, "Поля "
                        + "\"Логин\", \"Пароль\" и \"Повторите пароль\" "
                        + "не должны быть пустыми!");
                return;
            }//Проверка на заполненность в полях логин, пароль и повтор пароля
            if (!pas.equals(repPas)){
                JOptionPane.showMessageDialog(this, "Пароли не совпадают");
                return;
            }//Проверка на совпадение паролей
            List<User> listUser = Hiber.session.createQuery("from User "
                + "where login like '"+log+"'").list();
            if (listUser.isEmpty()){
            Cleint client = new Cleint(log,pas,fname,mname,lname,phon,mail);        
            Hiber.Save(client);
            } else {
                JOptionPane.showMessageDialog(this, "Такой логин уже занят!");
                return;
            }                    
        }
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private boolean checkMail(String text){
        String pattern = "^[__A-Za-z0-9-\\+]+(\\.[A-Za-z0-9-]+)*@"+
                "[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(text);
        return m.matches();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientRegDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientRegDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientRegDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientRegDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientRegDialog dialog = new ClientRegDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstField1;
    private javax.swing.JTextField LastField2;
    private javax.swing.JTextField LogField6;
    private javax.swing.JTextField MailField5;
    private javax.swing.JTextField MiddleField3;
    private javax.swing.JTextField PasField8;
    private javax.swing.JTextField PasRepField7;
    private javax.swing.JTextField PhoneField4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private void client(JTextField LogField6, JTextField PasField8, JTextField FirstField1, JTextField MiddleField3, JTextField LastField2, JTextField PhoneField4, JTextField MailField5) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
