package models;
// Generated 09.10.2020 11:17:03 by Hibernate Tools 4.3.1


import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="reeltordb"
)
public class Admin extends User implements java.io.Serializable {

    public Admin() {
    }

}


