package models;
// Generated 15.10.2020 14:03:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import models.User;

/**
 * Cleint generated by hbm2java
 */
@Entity
@Table(name="cleint"
    ,catalog="reeltordb"
)
public class Cleint extends User implements java.io.Serializable {

     private Long phone;
     private String email;
     private Set<Property> properties = new HashSet<Property>(0);

    public Cleint() {
    }

    public Cleint(String log, String pas, String fname, String mname, String lname, Integer phon, String mail) {
        this.setLogin(log);
       this.setPassword(pas);
       this.setFirstName(fname);
       this.setMiddleName(mname);
       this.setLastName(lname);
       this.phone = phone;
       this.email = email;
       this.properties = properties;
    }
   
    @Column(name="phone")
    public Long getPhone() {
        return this.phone;
    }
    
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cleint")
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }

}


