package models;
// Generated 09.10.2020 11:17:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cleint generated by hbm2java
 */
@Entity
@Table(name="cleint"
    ,catalog="reeltordb"
)
public class Cleint extends User implements java.io.Serializable {
    
    private Integer phone;
     private String email;

    public Cleint() {
    }


    public Cleint(String login, String password, String firstName, 
            String middleName, String lastName, Integer phone, String email) {
       this.setLogin(login);
       this.setPassword(password);
       this.setFirstName(firstName);
       this.setMiddleName(middleName);
       this.setLastName(lastName);
       this.phone = phone;
       this.email = email;
    }
    
    @Column(name="phone")
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


