package models;
// Generated 15.10.2020 14:03:26 by Hibernate Tools 4.3.1


import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Field generated by hbm2java
 */
@Entity
@Table(name="field"
    ,catalog="reeltordb"
)
public class Field extends Property implements java.io.Serializable {

    public Field() {        
    }
    
    public Field(Cleint cleint, String city, String street, 
            String numHouse, Double width, Double long_, Double area) {
       this.setCleint(cleint);
       this.setCity(city);
       this.setStreet(street);
       this.setNumHouse(numHouse);
       this.setWidth(width);
       this.setLong_(long_);
       this.setArea(area);        
    }

}


