package models;
// Generated 15.10.2020 14:03:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * House generated by hbm2java
 */
@Entity
@Table(name="house"
    ,catalog="reeltordb"
)
public class House extends Property implements java.io.Serializable {

     private String amountFloor;
     private String amountRoom;

    public House() {
    }
    
    public House(Cleint cleint, String city, String street, 
            String numHouse, Double width, Double long_, Double area, 
            String amountFloor, String amountRoom) {
       this.setCleint(cleint);
       this.setCity(city);
       this.setStreet(street);
       this.setNumHouse(numHouse);
       this.setWidth(width);
       this.setLong_(long_);
       this.setArea(area);
       this.amountFloor = amountFloor;
       this.amountRoom = amountRoom;
    }
    
    @Column(name="amountFloor", length=45)
    public String getAmountFloor() {
        return this.amountFloor;
    }
    
    public void setAmountFloor(String amountFloor) {
        this.amountFloor = amountFloor;
    }

    
    @Column(name="amountRoom", length=45)
    public String getAmountRoom() {
        return this.amountRoom;
    }
    
    public void setAmountRoom(String amountRoom) {
        this.amountRoom = amountRoom;
    }




}


