package models;
// Generated 09.10.2020 11:17:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Reeltor generated by hbm2java
 */
@Entity
@Table(name="reeltor"
    ,catalog="reeltordb"
)
public class Reeltor extends User implements java.io.Serializable {

     private Integer dealShare;

    public Reeltor() {
    }
    
    public Reeltor(String login, String password, String firstName, 
            String middleName, String lastName, Integer dealShare) {
       this.setLogin(login);
       this.setPassword(password);
       this.setFirstName(firstName);
       this.setMiddleName(middleName);
       this.setLastName(lastName);
       this.dealShare = dealShare;
    }


    @Column(name="dealShare")
    public Integer getDealShare() {
        return this.dealShare;
    }
    
    public void setDealShare(Integer dealShare) {
        this.dealShare = dealShare;
    }




}


